title:              Yuwon's blog
email:              whdbdnjs@hufs.ac.kr
description:        Im interested in solving problems of object detection using deep learning.
author:             Start Bootstrap
url:                "https://yuvvon.github.io"

# Social Profiles
twitter_username:    
github_username:     whdbdnjs@hufs.ac.kr
facebook_username:   
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
futrue: true
